version: '3.9'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - my-network
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  wordpress:
    build: ./wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    container_name: wordpress
    networks:
      - my-network
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  mariadb:
    container_name: mariadb
    ports:
      - "3306:3306"
    build:
      context: ./mariadb
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

networks:
  my-network:
    name: docker-network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/oabushar/data/wp
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/oabushar/data/sql